### ISSUE TITLE
Signed assembly

### ISSUE THREAD

**Issue by riesvriend** [ServiceStack/ServiceStack.Aws#12]
I would like to use ServiceStack.Aws in a project that uses the signed version of ServiceStack.

Can I ask to add a ServiceStack.Aws.Signed package to your builds, with dependency on ServiceStack.Signed.dll? 

Edit: I need ServiceStack.Aws to reference the signed ServiceStack assemblies, but I don't need it to be signed itself. In the mean time, I'll see what I can do based on the source.

Thx
Ries

**Comment by mythz** [comment]
No problems, I've just added support for ServiceStack.Aws.Signed which is now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

It will be available in the next v4.0.58 release which I'm hoping for either tomorrow or the day after.
