### ISSUE TITLE
(Bug) DynamoDB - Global Secondary Indexes do not require range/sort keys

### ISSUE THREAD

**Issue by mikepugh** [ServiceStack/ServiceStack.Aws#13]
Currently PocoDynamo will not let me create a global secondary index without a range/sort key specified.

GSI's with only a HashKey are supported by dynamo.

Code throws an error @ https://github.com/ServiceStack/ServiceStack.Aws/blob/af498f7e00672ba1fa34420e7a4cb7780e0e094a/src/ServiceStack.Aws/DynamoDb/DynamoMetadata.cs#L306-L314

**Comment by mythz** [comment]
Support for Global Indexes without a Range Key was added in this commit: https://github.com/ServiceStack/ServiceStack.Aws/commit/4e3f7b99177ef9a63508f42712ddea054ef421bd

This change is available from v4.0.61 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet)..

**Comment by mikepugh** [comment]
Excellent response time as always, thanks! :beers:
