### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by danpowell88** [ServiceStack/ServiceStack.Aws#24]
The .net object persistence model provided by AWS supports out of the box versioning, is something similar available in PocoDynamo.

I could find any code that dealt with versioning however I do see there is a RowVersion Data annotation

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBContext.VersionSupport.html

**Comment by mythz** [comment]
PocoDynamo doesn't have any explicit support for versioning although you should be able to use [Update with Conditional Expressions](https://github.com/ServiceStack/PocoDynamo#update-with-conditional-expressions) to only update a row based on a conditional expression.

Please note the [Issue Trackers is only for submitting reproducible issues](https://github.com/ServiceStack/Issues), please use the [Customer Forums](https://forums.servicestack.net/) of StackOverflow (inc. the `#servicestack` hashtag) for any other technical support issues whilst you can submit any feature requests on [ServiceStack's UserVoice](https://servicestack.uservoice.com/forums/176786-feature-requests).
