### ISSUE TITLE
PocoDynamo is not culture independant

### ISSUE THREAD

**Issue by grgouala** [ServiceStack/ServiceStack.Aws#25]
Due to the way the converter is implemented, the usage of PocoDynamo is culture dependant:

> return new AttributeValue { N = value.ToString() };

This is a bad pratice, since it requires to force the culture of the current thread to EN-US to avoid any conversion issues that you could get when executing the thread in another culture (like french, where the decimal separator is the comma).

**Comment by mythz** [comment]
Resolved in [this commit](https://github.com/ServiceStack/ServiceStack.Aws/commit/67ed8b8d7de3a18d92ba62ae239e6a42e3f47874). This change is available from v5 that's now [available on MyGet](http://docs.servicestack.net/myget). Please review [v5 changes](https://forums.servicestack.net/t/myget-pre-release-packages-upgraded-to-v5/4749) before upgrading.

FYI we're using [ServiceStack/Issues](https://github.com/ServiceStack/Issues) for any Issues on any .NET ServiceStack project.
