### ISSUE TITLE
PocoDynamo escaping characters

### ISSUE THREAD

**Issue by mikepugh** [ServiceStack/ServiceStack.Aws#9]
I'm evaluating the use of PocoDynamo vs the AWS SDK, so I've created a DynamoDB table and I'm using a composite key structure. My range key looks like "SOME_IMPORTANT_VALUE". I've noticed that PocoDynamo escapes the _ character due to the code @ https://github.com/ServiceStack/ServiceStack.Aws/blob/master/src/ServiceStack.Aws/DynamoDb/PocoDynamoExpression.cs#L378-L382

This causes PocoDynamo to not return any results on my queries. The regular AWS SDK works fine with the underscore character.

I couldn't find any documentation related to DynamoDB and the various escaped characters from PocoDynamoExpression.cs - is the escaping really necessary?

**Comment by mythz** [comment]
Yeah looks like strings don't need to be escaped, fixed in this commit: https://github.com/ServiceStack/ServiceStack.Aws/commit/153d34b5feceae7d9d0b4f31ccc5cdf09a86d955

This change is available from v4.0.57 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by mikepugh** [comment]
Confirmed that v4.0.57 works as expected now.

Thanks for the quick fix
